# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions

from . import stream_types, types
from .runtime import DoNotUseDirectlyCallManager, BamlCallOptions

class LlmResponseParser:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def GenerateElasticCertificationQuestion(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.ElasticQuestion:
        result = self.__options.merge_options(baml_options).parse_response(function_name="GenerateElasticCertificationQuestion", llm_response=llm_response, mode="request")
        return typing.cast(types.ElasticQuestion, result)

    def GenerateQuestionFromEnablementFile(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.ElasticMultipleTypeQuestion:
        result = self.__options.merge_options(baml_options).parse_response(function_name="GenerateQuestionFromEnablementFile", llm_response=llm_response, mode="request")
        return typing.cast(types.ElasticMultipleTypeQuestion, result)

    def ValidateGeneratedQuestion(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.ElasticMultipleTypeQuestionValidation:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ValidateGeneratedQuestion", llm_response=llm_response, mode="request")
        return typing.cast(types.ElasticMultipleTypeQuestionValidation, result)

    

class LlmStreamParser:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def GenerateElasticCertificationQuestion(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.ElasticQuestion:
        result = self.__options.merge_options(baml_options).parse_response(function_name="GenerateElasticCertificationQuestion", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.ElasticQuestion, result)

    def GenerateQuestionFromEnablementFile(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.ElasticMultipleTypeQuestion:
        result = self.__options.merge_options(baml_options).parse_response(function_name="GenerateQuestionFromEnablementFile", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.ElasticMultipleTypeQuestion, result)

    def ValidateGeneratedQuestion(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.ElasticMultipleTypeQuestionValidation:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ValidateGeneratedQuestion", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.ElasticMultipleTypeQuestionValidation, result)

    