###############################################################################
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml-py
#
###############################################################################

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code.
#
# ruff: noqa: E501,F401
# flake8: noqa: E501,F401
# pylint: disable=unused-import,line-too-long
# fmt: off
import baml_py
from enum import Enum

from pydantic import BaseModel, ConfigDict

from typing_extensions import TypeAlias, Literal
from typing import Dict, Generic, List, Optional, TypeVar, Union

from . import types
from .types import Checked, Check

###############################################################################
#
#  These types are used for streaming, for when an instance of a type
#  is still being built up and any of its fields is not yet fully available.
#
###############################################################################

T = TypeVar('T')
class StreamState(BaseModel, Generic[T]):
    value: T
    state: Literal["Pending", "Incomplete", "Complete"]


class ElasticQuestion(BaseModel):
    category: Optional[types.Category] = None
    question: Optional[str] = None
    endpoint: Optional[str] = None
    method: Optional[Union[Literal["GET"], Literal["POST"], Literal["PUT"], Literal["DELETE"]]] = None
    answer: Optional[str] = None

class ElasticSet(BaseModel):
    corpus: Optional["ElasticQuestion"] = None
    rating: Optional[Union[Literal["Good"], Literal["Bad"]]] = None
