# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from pydantic import BaseModel, ConfigDict

import baml_py

from . import types

StreamStateValueT = typing.TypeVar('StreamStateValueT')
class StreamState(BaseModel, typing.Generic[StreamStateValueT]):
    value: StreamStateValueT
    state: typing_extensions.Literal["Pending", "Incomplete", "Complete"]
# #########################################################################
# Generated classes (5)
# #########################################################################

class ElasticMultipleTypeQuestion(BaseModel):
    question: typing.Optional[str] = None
    answer: typing.Optional[str] = None
    questionType: typing.Optional[typing.Union[str, str]] = None

class ElasticMultipleTypeQuestionSet(BaseModel):
    questionClass: typing.Optional["ElasticMultipleTypeQuestion"] = None
    validationClass: typing.Optional["ElasticMultipleTypeQuestionValidation"] = None

class ElasticMultipleTypeQuestionValidation(BaseModel):
    isValid: typing.Optional[typing.Union[bool, bool]] = None
    reason: typing.Optional[str] = None
    location: typing.Optional[str] = None

class ElasticQuestion(BaseModel):
    category: typing.Optional[types.Category] = None
    question: typing.Optional[str] = None
    endpoint: typing.Optional[str] = None
    method: typing.Optional[typing.Union[str, str, str, str]] = None
    answer: typing.Optional[str] = None

class ElasticSet(BaseModel):
    corpus: typing.Optional["ElasticQuestion"] = None
    rating: typing.Optional[typing.Union[str, str]] = None

# #########################################################################
# Generated type aliases (0)
# #########################################################################
