# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from . import types
from . import stream_types


type_map = {

    "types.ElasticMultipleTypeQuestion": types.ElasticMultipleTypeQuestion,
    "stream_types.ElasticMultipleTypeQuestion": stream_types.ElasticMultipleTypeQuestion,

    "types.ElasticMultipleTypeQuestionSet": types.ElasticMultipleTypeQuestionSet,
    "stream_types.ElasticMultipleTypeQuestionSet": stream_types.ElasticMultipleTypeQuestionSet,

    "types.ElasticMultipleTypeQuestionValidation": types.ElasticMultipleTypeQuestionValidation,
    "stream_types.ElasticMultipleTypeQuestionValidation": stream_types.ElasticMultipleTypeQuestionValidation,

    "types.ElasticQuestion": types.ElasticQuestion,
    "stream_types.ElasticQuestion": stream_types.ElasticQuestion,

    "types.ElasticSet": types.ElasticSet,
    "stream_types.ElasticSet": stream_types.ElasticSet,


    "types.Category": types.Category,

}